// Generated by CoffeeScript 1.3.3
var Canvas, Image, Node, Rect, binPack, canvas, ctx, fs, imageDir;

fs = require('fs');

Canvas = require('canvas');

Image = Canvas.Image;

canvas = new Canvas(500, 500);

ctx = canvas.getContext('2d');

imageDir = __dirname + '/images/';

Rect = (function() {

  function Rect(x, y, w, h) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
  }

  Rect.prototype.contains = function(other) {
    return this.w >= other.w && this.h >= other.h;
  };

  Rect.prototype.equals = function(other) {
    return this.w === other.w && this.h === other.h;
  };

  Rect.prototype.toSimple = function() {
    return {
      x: this.x,
      y: this.y,
      w: this.w,
      h: this.h
    };
  };

  return Rect;

})();

Node = (function() {

  function Node() {
    this.left = null;
    this.right = null;
    this.rect = null;
    this.filled = false;
  }

  Node.prototype.insertRect = function(rect) {
    var heightDiff, me, widthDiff;
    if (this.left) {
      return this.left.insertRect(rect) || this.right.insertRect(rect);
    }
    if (this.filled) {
      return null;
    }
    if (!this.rect.contains(rect)) {
      return null;
    }
    if (rect.equals(this.rect)) {
      this.filled = true;
      return this;
    }
    this.left = new Node;
    this.right = new Node;
    widthDiff = this.rect.w - rect.w;
    heightDiff = this.rect.h - rect.h;
    me = this.rect;
    if (widthDiff > heightDiff) {
      this.left.rect = new Rect(me.x, me.y, rect.w, me.h);
      this.right.rect = new Rect(me.x + rect.w, me.y, me.w - rect.w, me.h);
    } else {
      this.left.rect = new Rect(me.x, me.y, me.w, rect.h);
      this.right.rect = new Rect(me.x, me.y + rect.h, me.w, me.h - rect.h);
    }
    return this.left.insertRect(rect);
  };

  return Node;

})();

binPack = function() {
  var data, image, images, img, map, node, out, r, rect, startNode, stream, _i, _len;
  images = fs.readdirSync(imageDir);
  console.log(images);
  startNode = new Node;
  startNode.rect = new Rect(0, 0, canvas.width, canvas.height);
  map = {};
  for (_i = 0, _len = images.length; _i < _len; _i++) {
    image = images[_i];
    data = fs.readFileSync(imageDir + image);
    img = new Image;
    img.src = data;
    rect = new Rect(0, 0, img.width, img.height);
    console.log("inserting: " + image + "...");
    node = startNode.insertRect(rect);
    if (node) {
      r = node.rect;
      map[image] = r.toSimple();
      ctx.drawImage(img, r.x, r.y);
    } else {
      throw "Not enough room for image: " + image;
    }
  }
  out = fs.createWriteStream(__dirname + '/output.png');
  stream = canvas.createPNGStream();
  console.log(map);
  return stream.on('data', function(chunk) {
    return out.write(chunk);
  });
};

binPack();
